// home collection

let CollectionShop = [
    {
        Id: 1,
        img: '../assets/image/product/img2.jpg',
        name: ' A set of art material Painting Framed Wall Art for Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 2,
        img: '../assets/image/product/img4.jpg',
        name: 'Painting of Victor harbor, Hong Kong Wall Art',
        price: '₹ 1200.00',
        discount: '₹ 1400.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 3,
        img: '../assets/image/product/img6.jpg',
        name: 'A set of art material Painting Framed Wall Art for Living Room',
        price: '₹ 2500.00',
        discount: '₹ 2800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 4,
        img: '../assets/image/product/img8.jpg',
        name: 'A set of art material Painting Framed Wall Art for Living Room.',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 5,
        img: '../assets/image/Arcylic/img2.jpg',
        name: 'Beautiful golden arcylic name plate framed designed for home',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 6,
        img: '../assets/image/Arcylic/img4.jpg',
        name: 'Arcylic name plate design frame sliver color square for home',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 7,
        img: '../assets/image/Arcylic/img6.jpg',
        name: 'Arcylic Name plate golden and black rounded for home wall',
        price: '₹ 1800.00',
        discount: '₹ 2000.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 8,
        img: '../assets/image/Arcylic/img8.jpg',
        name: 'Arcylic Name plate Frame Design for home | Design for Home wall',
        price: '₹ 2500.00',
        discount: '₹ 2850.00',
        link: '../components/productFirst.html',
    },
];

//murals-arrivasl

let arrivalCollection = [
    {
        Id: 1,
        img: '../assets/image/Moral/image1.jpg',
        name: 'Autumn Nature Painting Wall Decor Wall Art for Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 2,
        img: '../assets/image/Moral/image3.jpg',
        name: 'Maple Leaf Wall Decor Wall Art for Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 3,
        img: '../assets/image/Moral/image5.jpg',
        name: 'white tiger Wall Decor wall Art for Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 4,
        img: '../assets/image/Moral/image7.jpg',
        name: 'glass horse painting Wall Decor Wall Art for Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 5,
        img: '../assets/image/Moral/image9.jpg',
        name: 'Lion Wall Decor Wall Art for Living Room Ready to Hang.',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 6,
        img: '../assets/image/Moral/image11.jpg',
        name: 'City Pulse: Metropolis Artwork Wall Art for Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 7,
        img: '../assets/image/Moral/image13.jpg',
        name: 'colorful Parrot on a twig of a tree Wall Art for Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
    {
        Id: 8,
        img: '../assets/image/Moral/image15.jpg',
        name: '3 Panels Red fdiscounter Wall Decor Wall Art for Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        link: '../components/productFirst.html',
    },
];


// canvas data
let shopItemsData = [

    {
        id: 1,
        name: 'beautifull wall canvas wall Images',
        price: '₹ 3500.00',
        discount: '₹ 4000.00',
        img: '../assets/image/Canvas/image1.webp',
    },
    {
        id: 2,
        name: 'beautifull wall canvas wall Images',
        price: '₹ 3500.00',
        discount: '₹ 4000.00',
        img: '../assets/image/Canvas/image1.webp',
    },
    {
        id: 3,
        name: 'beautifull wall canvas wall Images',
        price: '₹ 3500.00',
        discount: '₹ 4000.00',
        img: '../assets/image/Canvas/image1.webp',
    },
    {
        id: 4,
        name: 'beautifull wall canvas wall Images',
        price: '₹ 3500.00',
        discount: '₹ 4000.00',
        img: '../assets/image/Canvas/image1.webp',
    },

];

// wedding data
let weddingItemsData = [
    {
        id: 1,
        name: 'Customized Neon For Couple Sign | Wedding Name Neon ',
        price: '₹399',
        discount: '₹500',
        img: '../assets/image/wedding-neon/image1.jpg',
    },
    {
        id: 2,
        name: 'Wedding Custom Mr & M₹ Neon Sign Flex Led Neon Light Sign ',
        price: '₹2999',
        discount: '₹5000',
        img: '../assets/image/wedding-neon/image2.jpg',
    },
    {
        id: 3,
        name: 'Better Together Wedding flex Custom Neon Sign Light ',
        price: '₹1550',
        discount: '₹2000',
        img: '../assets/image/wedding-neon/image3.jpg',
    },
    {
        id: 4,
        name: 'Good wibes only Wedding flex Custom Neon Sign Light ',
        price: '₹4250',
        discount: '₹5000',
        img: '../assets/image/wedding-neon/image4.jpg',
    },
    {
        id: 5,
        name: 'Happily Ever After Wedding flex Custom Neon Sign Light ',
        price: '₹4050',
        discount: '₹4550',
        img: '../assets/image/wedding-neon/image5.jpg',
    },
    {
        id: 6,
        name: 'Lets Dance Wedding flex Custom Neon Sign Light ',
        price: '₹2000',
        discount: '₹3500',
        img: '../assets/image/wedding-neon/image6.jpg',
    },
    {
        id: 7,
        name: 'Lets Celebrate Wedding flex Custom Neon Sign Light ',
        price: '₹3500',
        discount: '₹4000',
        img: '../assets/image/wedding-neon/image7.jpg',
    },
    {
        id: 8,
        name: 'Engaged Custom Neon flex Wedding Sign light ',
        price: '₹3500',
        discount: '₹4000',
        img: '../assets/image/wedding-neon/image8.jpg',
    },
    {
        id: 9,
        name: 'The Adventure beings Wedding flex Custom Neon Sign Light ',
        price: '₹3500',
        discount: '₹4000',
        img: '../assets/image/wedding-neon/image9.jpg',
    },
    {
        id: 10,
        name: 'Drunk in love Wedding flex Custom Neon Sign Light ',
        price: '₹2500',
        discount: '₹3000',
        img: '../assets/image/wedding-neon/image10.jpg',
    },
    {
        id: 11,
        name: 'Marry me love Wedding flex Custom Neon Sign Light ',
        price: '₹3000',
        discount: '₹3500',
        img: '../assets/image/wedding-neon/image11.webp',
    },
    {
        id: 12,
        name: 'will you marry me love Wedding flex Custom Neon Sign Light ',
        price: '₹4500',
        low: '₹5000',
        img: '../assets/image/wedding-neon/image12.webp',
    },
    {
        id: 13,
        name: 'couple love Wedding flex Custom Neon Sign Light ',
        price: '₹3200',
        discount: '₹4500',
        img: '../assets/image/wedding-neon/image13.webp',
    },
    {
        id: 14,
        name: 'oh baby love Wedding flex Custom Neon Sign Light ',
        price: '₹2800',
        discount: '₹3000',
        img: '../assets/image/wedding-neon/image14.webp',
    },
    {
        id: 15,
        name: 'heart love Wedding flex Custom Neon Sign Light ',
        price: '₹2800',
        discount: '₹3000',
        img: '../assets/image/wedding-neon/image15.webp',
    },
    {
        id: 16,
        name: 'better together Wedding flex Custom Neon Sign Light ',
        price: '₹3600',
        discount: '₹4000',
        img: '../assets/image/wedding-neon/image16.jpg',
    },
];

// religious Arcylic data

let ProductStore = [
    {
        id: 1,
        name: 'Om Metal Wall ArtWall Decor | Living Room Outdoor Decoration',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        src: '../assets/image/Religious-acrylic/image1.jpg',
        img: '../assets/image/Religious-acrylic/image2.jpg',
    },
    {
        id: 2,
        name: 'buddha Metal Wall ArtWall Decor | Living Room Outdoor Decoration',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        src: '../assets/image/Religious-acrylic/image3.jpg',
        img: '../assets/image/Religious-acrylic/image4.jpg',
    },
    {
        id: 3,
        name: 'Buddha Metal Wall ArtWall Decor | Living Room Outdoor Decoration',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        src: '../assets/image/Religious-acrylic/image5.jpg',
        img: '../assets/image/Religious-acrylic/image6.jpg',
    },
    {
        id: 4,
        name: 'Meditation Wall ArtWall Decor | Living Room Outdoor Decoration',
        price: '₹ 900.0',
        discount: '₹ 1100.0',
        src: '../assets/image/Religious-acrylic/image7.jpg',
        img: '../assets/image/Religious-acrylic/image8.jpg',
    },
    {
        id: 5,
        name: 'Om Metal Wall ArtWall Decor | Living Room Outdoor Decoration',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        src: '../assets/image/Religious-acrylic/image9.jpg',
        img: '../assets/image/Religious-acrylic/image10.jpg',
    },
    {
        id: 6,
        name: 'Swastik Metal Wall ArtWall Decor | Living Room Outdoor Decoration',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        src: '../assets/image/Religious-acrylic/image12.jpg',
        img: '../assets/image/Religious-acrylic/image11.jpg',
    },
    {
        id: 7,
        name: 'Shree Ram Wall ArtWall Decor | Living Room Outdoor Decoration',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        src: '../assets/image/Religious-acrylic/image14.jpg',
        img: '../assets/image/Religious-acrylic/image13.jpg',
    },
    {
        id: 8,
        name: 'Shree Ganeshay Namah 3D Morden Round Acrylic Wall Art',
        price: '₹ 500.0',
        discount: '₹ 800.0',
        src: '../assets/image/Religious-acrylic/image15.jpg',
        img: '../assets/image/Religious-acrylic/image16.jpg',
    },
    {
        id: 9,
        name: 'Herrlich Homes Buddha Metal Wall Art | Yoga Studio Wall Art',
        price: '₹ 1285.0',
        discount: '₹ 1550.0',
        src: '../assets/image/Religious-acrylic/image17.jpg',
        img: '../assets/image/Religious-acrylic/image18.jpg',
    },
    {
        id: 10,
        name: 'Lord Shiva Metal Wall Art for Home & Office Decor ',
        price: '₹ 2199.0',
        discount: '₹ 2500.0',
        src: '../assets/image/Religious-acrylic/image19.jpg',
        img: '../assets/image/Religious-acrylic/image20.jpg',
    },
    {
        id: 11,
        name: 'Lord Shree Ram Backlit Wooden Wall Decor for Home ',
        price: '₹ 2259.0',
        discount: '₹ 2450.0',
        src: '../assets/image/Religious-acrylic/image21.jpg',
        img: '../assets/image/Religious-acrylic/image22.jpg',
    },
    {
        id: 12,
        name: 'Lord Shree Ram Backlit Wooden Wall Decor for Home ',
        price: '₹ 2099.0',
        discount: '₹ 2500.0',
        src: '../assets/image/Religious-acrylic/image23.jpg',
        img: '../assets/image/Religious-acrylic/image24.jpg',
    },
];

// Neon data

let neonStore = [
    {
        id: 1,
        name: 'David bubblegum | UV print with Neon for Room',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        img: '../assets/image/slider/img1.jpg',
    },
    {
        id: 2,
        name: 'Digital pop art with Neon design for room',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        img: '../assets/image/slider/img2.jpg',
    },
    {
        id: 3,
        name: 'Monalisa | This is not Art neon light design for room',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        img: '../assets/image/slider/img3.jpg',
    },
    {
        id: 4,
        name: 'Bob Marley Jadi booty Design Neon light design for room',
        price: '₹ 900.0',
        discount: '₹ 1100.0',
        img: '../assets/image/slider/img4.jpg',
    },
    {
        id: 5,
        name: 'korean love sign shape Design Neon light',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        img: '../assets/image/slider/img5.jpg',
    },
    {
        id: 6,
        name: 'Hand Shape Neon Light Design for room',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        img: '../assets/image/slider/img6.jpg',
    },
    {
        id: 7,
        name: 'A₹enal logo | backlit neon design for room',
        price: '₹ 800.0',
        discount: '₹ 1000.0',
        img: '../assets/image/slider/img7.jpg',
    },
    {
        id: 8,
        name: 'Footbaal Club Neon light design for room',
        price: '₹ 500.0',
        discount: '₹ 800.0',
        img: '../assets/image/slider/img8.jpg',
    },
    {
        id: 9,
        name: 'fries and drink neon Design for room and ba₹',
        price: '₹ 1285.0',
        discount: '₹ 1550.0',
        img: '../assets/image/slider/img9.jpg',
    },
    {
        id: 10,
        name: 'no music no life Neon light design for room',
        price: '₹ 2199.0',
        discount: '₹ 2500.0',
        img: '../assets/image/slider/img10.jpg',
    },
    {
        id: 11,
        name: 'Avenge₹ logo Neon design for room and office',
        price: '₹ 2259.0',
        discount: '₹ 2450.0',
        img: '../assets/image/slider/img11.jpg',
    },
    {
        id: 12,
        name: 'Green leaves Neon light design for room and office',
        price: '₹ 2099.0',
        discount: '₹ 2500.0',
        img: '../assets/image/slider/img12.jpg',
    },
];

// Blockout data

let BlockoutStore = [
    {
        id: 1,
        name: '',
        price: '₹ 2800.0',
        discount: '₹ 3200.0',
        img: '../assets/image/Blockout/image1.jpg',
        src: '../assets/image/Blockout/image2.jpg',
    },
    {
        id: 2,
        name: '',
        price: '₹ 2800.0',
        discount: '₹ 3200.0',
        img: '../assets/image/Blockout/image4.jpg',
        src: '../assets/image/Blockout/image3.jpg',
    },
    {
        id: 3,
        name: '',
        price: '₹ 2800.0',
        discount: '₹ 3200.0',
        img: '../assets/image/Blockout/image6.jpg',
        src: '../assets/image/Blockout/image5.jpg',
    },
    {
        id: 4,
        name: '',
        price: '₹ 2800.0',
        discount: '₹ 3200.0',
        img: '../assets/image/Blockout/image7.jpg',
        src: '../assets/image/Blockout/image8.jpg',
    },
];

// Neons data

let NeonItemsData = [
    {
        id: 1,
        name: 'Adventure is out here Neon Sign Light',
        price: '₹ 1259.0',
        discount: '₹ 3200.0',
        img: '../assets/image/Neon/neon5.jpg',
        src: '../assets/image/Neon/neon6.jpg',
    },
    {
        id: 2,
        name: 'Triangle Shape model Neon sign Light',
        price: '₹ 1150.0',
        discount: '₹ 3200.0',
        img: '../assets/image/Neon/neon7.jpg',
        src: '../assets/image/Neon/neon8.jpg',
    },
    {
        id: 3,
        name: 'Alien animie Neon sign Light for room',
        price: '₹ 1299.0',
        discount: '₹ 3200.0',
        img: '../assets/image/Neon/neon9.jpg',
        src: '../assets/image/Neon/neon10.jpg',
    },
    {
        id: 4,
        name: 'Eyes Neon Sign Light for home room',
        price: '₹ 2800.0',
        discount: '₹ 3200.0',
        img: '../assets/image/Neon/neon11.jpg',
        src: '../assets/image/Neon/neon12.jpg',
    },
];

// Anime data

let animeItemsData = [
    {
        id: 1,
        name: 'Naruto Neon Sign Light | Anime Neon Light',
        price: '₹ 1259.00',
        discount: '₹ 3200.00',
        img: '../assets/image/Animation/image1.jpg',
    },
    {
        id: 2,
        name: 'Luffy Skull Neon Sign Light | Anime Neon Light',
        price: '₹ 1150.00',
        discount: '₹ 3200.00',
        img: '../assets/image/Animation/image2.webp',
    },
    {
        id: 3,
        name: 'pikachu Neon sign Light  | Anime Neon Light',
        price: '₹ 1299.00',
        discount: '₹ 3200.00',
        img: '../assets/image/Animation/image3.webp',
    },
    {
        id: 4,
        name: ' Nezuko Neon sign Light | Anime Neon Light',
        price: '₹ 2800.00',
        discount: '₹ 3200.00',
        img: '../assets/image/Animation/image4.webp',
    },
    {
        id: 5,
        name: ' Anime Neon Sign Neon | Anime LED Neon Sign Light',
        price: '₹ 3800.00',
        discount: '₹ 4200.00',
        img: '../assets/image/Animation/image5.jpg',
    },
    {
        id: 6,
        name: ' Anime Neon Sign | Anime Neon Logo Sign Kids Room',
        price: '₹ 1800.00',
        discount: '₹ 2200.00',
        img: '../assets/image/Animation/image6.webp',
    },
    {
        id: 7,
        name: ' Doremon Neon sign Light | Anime Neon Light',
        price: '₹ 2800.00',
        discount: '₹ 3200.00',
        img: '../assets/image/Animation/image7.webp',
    },
    {
        id: 8,
        name: ' Mickey Mouse Neon sign Light | Anime Neon Light',
        price: '₹ 1600.00',
        discount: '₹ 2000.00',
        img: '../assets/image/Animation/image8.jpg',
    },
    {
        id: 9,
        name: 'Ghost Neon Sign | Funny Anime Neon Light',
        price: '₹ 2400.00',
        discount: '₹ 2800.00',
        img: '../assets/image/Animation/image9.jpg',
    },
    {
        id: 10,
        name: 'cat  Neon Sign Light | Anime Neon Led Light',
        price: '₹ 1600.00',
        discount: '₹ 2000.00',
        img: '../assets/image/Animation/image10.jpg',
    },
    {
        id: 11,
        name: 'Goomba Neon Sign, Mario Bros Neon Light ',
        price: '₹ 2000.00',
        discount: '₹ 2400.00',
        img: '../assets/image/Animation/image11.jpg',
    },
    {
        id: 12,
        name: 'Mario Man LED Neon Sign | Anime Neon Light ',
        price: '₹ 2000.00',
        discount: '₹ 2400.00',
        img: '../assets/image/Animation/image12.jpg',
    },
    {
        id: 13,
        name: 'Neonium Anime Turtle Neon sign | Cartoon LED Neon Sign ',
        price: '₹ 3200.00',
        discount: '₹ 3500.00',
        img: '../assets/image/Animation/image13.jpeg',
    },
    {
        id: 14,
        name: 'Playboy bunny Neon sign | Cartoon LED Neon Sign ',
        price: '₹ 2800.00',
        discount: '₹ 3000.00',
        img: '../assets/image/Animation/image14.jpg',
    },
    {
        id: 15,
        name: 'spider Neon sign | Cartoon LED Neon Sign light',
        price: '₹ 2400.00',
        discount: '₹ 2650.00',
        img: '../assets/image/Animation/image15.jpg',
    },
    {
        id: 16,
        name: 'Superman Neon sign | Cartoon LED Neon Sign light',
        price: '₹ 3500.00',
        discount: '₹ 4850.00',
        img: '../assets/image/Animation/image16.jpg',
    },
];


// Mural data

let muralItemsData = [
    {
        id: 1,
        name: 'Autumn Nature Painting Wall Decor Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image1.jpg',
        img: '../assets/image/Moral/image2.jpg',
    },
    {
        id: 2,
        name: 'Maple Leaf Wall Decor Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image3.jpg',
        img: '../assets/image/Moral/image4.jpg',
    },
    {
        id: 3,
        name: 'White Tiger Wall Decor Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image5.jpg',
        img: '../assets/image/Moral/image6.jpg',
    },
    {
        id: 4,
        name: 'Glass Horse Painting Wall Decor Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image7.jpg',
        img: '../assets/image/Moral/image8.jpg',
    },
    {
        id: 5,
        name: 'Lion Wall Decor Wall Art For Living Room Ready To Hang.',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image9.jpg',
        img: '../assets/image/Moral/image10.jpg',
    },
    {
        id: 6,
        name: 'City Pulse: Metropolis Artwork Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image11.jpg',
        img: '../assets/image/Moral/image12.jpg',
    },
    {
        id: 7,
        name: 'Colorful Parrot On A Twig Of A Tree Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image13.jpg',
        img: '../assets/image/Moral/image14.png',
    },
    {
        id: 8,
        name: '3 Panels Red Fdiscounter Wall Decor Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image15.jpg',
        img: '../assets/image/Moral/image16.png',
    },
    {
        id: 9,
        name: '3 Panels birds  Wall Decor Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image18.jpg',
        img: '../assets/image/Moral/image17.jpg',
    },
    {
        id: 10,
        name: '3 Panels flower  Wall Decor Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image20.jpg',
        img: '../assets/image/Moral/image19.jpg',
    },
    {
        id: 11,
        name: '3 Panels bottle Wall Decor Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image22.jpg',
        img: '../assets/image/Moral/image21.jpg',
    },
    {
        id: 12,
        name: '3 Panels tiger Wall Decor Wall Art For Living Room',
        price: '₹ 1500.00',
        discount: '₹ 1800.00',
        src: '../assets/image/Moral/image24.jpg',
        img: '../assets/image/Moral/image23.jpg',
    },
]


let religiousItemsData = [
    {
        id: 1,
        name: 'Religious Hands Praying LED Neon Light Sign',
        price: '₹ 1200.0',
        discount: '₹ 1400.0',
        img: '../assets/image/Religious/img1.jpg',
    },
    {
        id: 2,
        name: 'Stairway To Heaven Neon Light Custom made light',
        price: '₹ 1400.0',
        discount: '₹ 1500.0',
        img: '../assets/image/Religious/img2.jpg',
    },
    {
        id: 3,
        name: 'Christian Cross Neon Light, Neon Sign Light Decor',
        price: '₹ 1100.0',
        discount: '₹ 1300.0',
        img: '../assets/image/Religious/img3.jpg',
    },
    {
        id: 4,
        name: 'Crying Girl neon Light Decor for Home | Room',
        price: '₹ 1200.0',
        discount: '₹ 1400.0',
        img: '../assets/image/Religious/img4.jpg',
    },
    {
        id: 5,
        name: 'Cross Neon Sign Light Decor for home and room',
        price: '₹ 1500.0',
        discount: '₹ 1800.0',
        img: '../assets/image/Religious/img5.jpg',
    },
    {
        id: 6,
        name: 'Katana Led Neon Sign | Wall Decor | Wall Sign | Neon Lights',
        price: '₹ 1500.0',
        discount: '₹ 1650.0',
        img: '../assets/image/Religious/img6.jpg',
    },
    {
        id: 7,
        name: 'Om Neon Sign Light Decor for home and room | temples',
        price: '₹ 1600.0',
        discount: '₹ 1800.0',
        img: '../assets/image/Religious/img7.jpg',
    },
    {
        id: 8,
        name: 'Lotus Pose Yoga Neon Sign | Meditation Neon light',
        price: '₹ 1500.0',
        discount: '₹ 1800.0',
        img: '../assets/image/Religious/img8.jpg',
    },
    {
        id: 9,
        name: 'OM Neon Light Purple color Design Home | Rooms',
        price: '₹ 1200.0',
        discount: '₹ 1400.0',
        img: '../assets/image/Religious/img9.jpg',
    },
    {
        id: 10,
        name: 'Meditation Neon Night purple color design for home',
        price: '₹ 1400.0',
        discount: '₹ 1500.0',
        img: '../assets/image/Religious/img10.jpg',
    },
    {
        id: 11,
        name: 'Shree Ram neon dign light decor for Home and room ',
        price: '₹ 1100.0',
        discount: '₹ 1300.0',
        img: '../assets/image/Religious/img11.jpg',
    },
    {
        id: 12,
        name: 'om namah shivaye neon dign light decor for Home and room ',
        price: '₹ 1500.0',
        discount: '₹ 1800.0',
        img: '../assets/image/Religious/img12.jpg',
    },
    {
        id: 13,
        name: 'god plans Neon Sign Light Decor for home and room',
        price: '₹ 1450.0',
        discount: '₹ 1640.0',
        img: '../assets/image/Religious/img13.jpg',
    },
    {
        id: 14,
        name: 'Hands Neon Sign | Wall Decor | Wall Sign | Neon Lights',
        price: '₹ 1400.0',
        discount: '₹ 1650.0',
        img: '../assets/image/Religious/img14.jpg',
    },
    {
        id: 15,
        name: 'Ganesh Neon Sign Light Decor for home and room | temples',
        price: '₹ 1600.0',
        discount: '₹ 1800.0',
        img: '../assets/image/Religious/img15.jpg',
    },
    {
        id: 16,
        name: 'Swastik Neon light | swastik neon light decor for home',
        price: '₹ 1500.0',
        discount: '₹ 1800.0',
        img: '../assets/image/Religious/img16.jpg',
    },
];


//search product



